export const ActivitiesArray = [
  "Clean your wardrobe",
  "Shop online",
  "Call a relative",
  "Call a friend",
  "Replant some flowers",
  "Wash your hands",
  "Learn how to knit",
  "Check your utility contract",
  "Invite for AW online",
  "Bake a cake",
  "Clean your oven",
  "Tidy up at home",
  "Do yoga",
  "Make a cake",
  "Make some food",
  "Plan for non-quarantine",
  "Arrange photos",
  "Clean the stove filter",
  "Do home-spaaing",
  "Arrange photos",
  "Play table-tennis",
  "Play cards",
  "Have some coffe",
  "Read a book"
]
