export const answers = [
  "I think, yes!",
  "Ask me later I am tired",
  "Try to google it",
  "Sounds reasonable",
  "Unpredictable outcome",
  "Concentrate and ask again",
  "Don’t count on it",
  "It is certain",
  "Most likely",
  "Almost impossible",
  "Everythink is possible",
  "My reply is no",
  "Universe say no",
  "Outlook good",
  "Fortune is on your side",
  "Signs point to yes",
  "Will you dare?",
  "Without a doubt",
  "Yes",
  "No",
  "Force is with you!",
  "You may rely on it",
  "Go for it!",
  "Let it go",
  "It will be fine, soon...",
  "What your heart tells?",
  "Do what fills right",
  "Do not focus on it!",
  "Leave it for later",
  "Ask a human for advice!",
  "Do not overthink",
  "I am just a ball",
  "Flip a coin",
  "Explore it deeper",
  "Take your chances",
  "Think twice before",
];
